import type { Course, CourseId } from "./types";

/**
 * The curriculum map — transcribed exactly from .claude/docs/CURRICULUM.md
 * §14 (Building Blocks), §15 (Real World Extraction), §17 (prerequisite
 * graph), and §23 (final curriculum map). Do not reorder, renumber, or
 * retitle: these slugs are both route segments and Dexie persistence keys
 * (see src/persistence/db.ts's CurriculumProgress), so a rename after
 * release orphans progress rows and breaks bookmarks.
 *
 * This is the v3 curriculum (79 entries: 47 Building Blocks + 32 Real World
 * Extraction), migrated from the v1 26+5 map per §21.4. Only two entries
 * have a real `chapterDefinitionId` in 3.0.0 — every other entry is a real
 * curriculum row with no authored lesson behind it yet
 * (src/content/chapters/index.ts's chapterRegistry stays throwaway/dummy
 * content until real authoring lands). `prerequisiteSlugs` is populated
 * from §17's part/group/tier-level graph (chapters within a
 * part/group/tier are strictly sequential) but nothing reads it yet — see
 * .claude/docs/RELEASE_3.0.0_LEARNING_PATH.md §6, "Locked chapters".
 */
export const courses: Record<CourseId, Course> = {
  "building-blocks": {
    id: "building-blocks",
    title: "Building Blocks",
    subtitle:
      "One concept at a time, with a constrained palette and validation that explains itself.",
    sections: [
      {
        id: "bb-part-0",
        label: "Part 0",
        title: "Foundations",
        summary:
          "Orientation - the learner needs to know what the discipline is, what the product " +
          "expects of them, and how interview and production registers differ, before any " +
          "real content.",
        chapters: [
          {
            slug: "0-1-welcome-to-scalecraft",
            number: "0.1",
            title: "Welcome to ScaleCraft",
            kind: "chapter",
            chapterDefinitionId: "bb-0-1-welcome",
            estimatedMinutes: 10,
            difficulty: "foundational",
            prerequisiteSlugs: [],
            domain: null,
          },
          {
            slug: "0-2-what-is-system-design",
            number: "0.2",
            title: "What is System Design?",
            kind: "chapter",
            chapterDefinitionId: "bb-0-2-what-is-system-design",
            estimatedMinutes: 15,
            difficulty: "foundational",
            prerequisiteSlugs: ["0-1-welcome-to-scalecraft"],
            domain: null,
          },
          {
            slug: "0-3-interview-design-vs-production-engineering",
            number: "0.3",
            title: "Interview Design vs. Production Engineering",
            kind: "chapter",
            chapterDefinitionId: "bb-0-3-interview-design-vs-production-engineering",
            estimatedMinutes: 15,
            difficulty: "foundational",
            prerequisiteSlugs: ["0-2-what-is-system-design"],
            domain: null,
          },
          {
            slug: "0-4-the-system-design-lifecycle",
            number: "0.4",
            title: "The System Design Lifecycle",
            kind: "chapter",
            chapterDefinitionId: "bb-0-4-the-system-design-lifecycle",
            estimatedMinutes: 15,
            difficulty: "foundational",
            prerequisiteSlugs: ["0-3-interview-design-vs-production-engineering"],
            domain: null,
          },
        ],
      },
      {
        id: "bb-part-1",
        label: "Part 1",
        title: "Engineering Design Process",
        summary:
          "The defining structural bet of the curriculum: the design method is taught on tiny, " +
          "familiar systems using only the three primitive components, so the method itself " +
          "is the only new material.",
        chapters: [
          {
            slug: "1-1-understanding-the-problem",
            number: "1.1",
            title: "Understanding the Problem",
            kind: "chapter",
            chapterDefinitionId: null,
            estimatedMinutes: 20,
            difficulty: "foundational",
            prerequisiteSlugs: ["0-4-the-system-design-lifecycle"],
            domain: null,
          },
          {
            slug: "1-2-functional-requirements",
            number: "1.2",
            title: "Functional Requirements",
            kind: "chapter",
            chapterDefinitionId: null,
            estimatedMinutes: 15,
            difficulty: "foundational",
            prerequisiteSlugs: ["1-1-understanding-the-problem"],
            domain: null,
          },
          {
            slug: "1-3-non-functional-requirements",
            number: "1.3",
            title: "Non-functional Requirements",
            kind: "chapter",
            chapterDefinitionId: null,
            estimatedMinutes: 20,
            difficulty: "foundational",
            prerequisiteSlugs: ["1-2-functional-requirements"],
            domain: null,
          },
          {
            slug: "1-4-estimating-scale",
            number: "1.4",
            title: "Estimating Scale",
            kind: "chapter",
            chapterDefinitionId: null,
            estimatedMinutes: 25,
            difficulty: "foundational",
            prerequisiteSlugs: ["1-3-non-functional-requirements"],
            domain: null,
          },
          {
            slug: "1-5-numbers-every-engineer-should-know",
            number: "1.5",
            title: "Numbers Every Engineer Should Know",
            kind: "chapter",
            chapterDefinitionId: null,
            estimatedMinutes: 20,
            difficulty: "foundational",
            prerequisiteSlugs: ["1-4-estimating-scale"],
            domain: null,
          },
          {
            slug: "1-6-drawing-the-first-architecture",
            number: "1.6",
            title: "Drawing the First Architecture",
            kind: "chapter",
            chapterDefinitionId: null,
            estimatedMinutes: 30,
            difficulty: "foundational",
            prerequisiteSlugs: ["1-5-numbers-every-engineer-should-know"],
            domain: null,
          },
          {
            slug: "1-7-identifying-bottlenecks",
            number: "1.7",
            title: "Identifying Bottlenecks",
            kind: "chapter",
            chapterDefinitionId: null,
            estimatedMinutes: 25,
            difficulty: "foundational",
            prerequisiteSlugs: ["1-6-drawing-the-first-architecture"],
            domain: null,
          },
          {
            slug: "1-8-engineering-trade-offs",
            number: "1.8",
            title: "Engineering Trade-offs",
            kind: "chapter",
            chapterDefinitionId: null,
            estimatedMinutes: 20,
            difficulty: "foundational",
            prerequisiteSlugs: ["1-7-identifying-bottlenecks"],
            domain: null,
          },
          {
            slug: "1-9-deep-dive-methodology",
            number: "1.9",
            title: "Deep Dive Methodology",
            kind: "chapter",
            chapterDefinitionId: null,
            estimatedMinutes: 20,
            difficulty: "foundational",
            prerequisiteSlugs: ["1-8-engineering-trade-offs"],
            domain: null,
          },
          {
            slug: "1-10-communicating-and-defending-a-design",
            number: "1.10",
            title: "Communicating & Defending a Design",
            kind: "chapter",
            chapterDefinitionId: null,
            estimatedMinutes: 20,
            difficulty: "foundational",
            prerequisiteSlugs: ["1-9-deep-dive-methodology"],
            domain: null,
          },
          {
            slug: "1-11-driving-a-system-design-interview",
            number: "1.11",
            title: "Driving a System Design Interview",
            kind: "chapter",
            chapterDefinitionId: null,
            estimatedMinutes: 30,
            difficulty: "foundational",
            // §17: optional chapter, gates nothing - nothing lists this slug
            // as a prerequisite. Part 2 hangs off 1.10, not off this one.
            prerequisiteSlugs: ["1-10-communicating-and-defending-a-design"],
            domain: null,
          },
        ],
      },
      {
        id: "bb-part-2",
        label: "Part 2",
        title: "Journey of a Request",
        summary:
          "One request is traced from keystroke to response so every Part 3 block later " +
          "lands at a known address.",
        chapters: [
          {
            slug: "2-1-from-browser-to-backend",
            number: "2.1",
            title: "From Browser to Backend",
            kind: "chapter",
            chapterDefinitionId: null,
            estimatedMinutes: 20,
            difficulty: "foundational",
            // §17: hangs off 1.10 - 1.11 is optional and gates nothing.
            prerequisiteSlugs: ["1-10-communicating-and-defending-a-design"],
            domain: null,
          },
          {
            slug: "2-2-where-can-things-go-wrong",
            number: "2.2",
            title: "Where Can Things Go Wrong?",
            kind: "chapter",
            chapterDefinitionId: null,
            estimatedMinutes: 20,
            difficulty: "foundational",
            prerequisiteSlugs: ["2-1-from-browser-to-backend"],
            domain: null,
          },
          {
            slug: "2-3-evolution-of-modern-architectures",
            number: "2.3",
            title: "Evolution of Modern Architectures",
            kind: "chapter",
            chapterDefinitionId: null,
            estimatedMinutes: 20,
            difficulty: "foundational",
            prerequisiteSlugs: ["2-2-where-can-things-go-wrong"],
            domain: null,
          },
        ],
      },
      {
        id: "bb-group-a",
        label: "Group A",
        title: "Core Infrastructure",
        summary:
          "Just enough networking, naming, and routing to reason about everything above it - " +
          "the trust perimeter and the request's first hops.",
        chapters: [
          {
            slug: "3-1-networking-fundamentals",
            number: "3.1",
            title: "Networking Fundamentals",
            kind: "chapter",
            chapterDefinitionId: null,
            estimatedMinutes: 25,
            difficulty: "foundational",
            prerequisiteSlugs: ["2-3-evolution-of-modern-architectures"],
            domain: null,
          },
          {
            slug: "3-2-dns",
            number: "3.2",
            title: "DNS",
            kind: "chapter",
            chapterDefinitionId: null,
            estimatedMinutes: 20,
            difficulty: "foundational",
            prerequisiteSlugs: ["3-1-networking-fundamentals"],
            domain: null,
          },
          {
            slug: "3-3-reverse-proxy",
            number: "3.3",
            title: "Reverse Proxy",
            kind: "chapter",
            chapterDefinitionId: null,
            estimatedMinutes: 20,
            difficulty: "foundational",
            prerequisiteSlugs: ["3-2-dns"],
            domain: null,
          },
          {
            slug: "3-4-load-balancer",
            number: "3.4",
            title: "Load Balancer",
            kind: "chapter",
            // Re-homed from v1's 1.2 Load Balancing per §21.4's mapping
            // table (1.2 -> 3.4) - the one authored placeholder in BB.
            chapterDefinitionId: "bb-dummy-1",
            estimatedMinutes: 35,
            difficulty: "foundational",
            prerequisiteSlugs: ["3-3-reverse-proxy"],
            domain: null,
          },
          {
            slug: "3-5-api-gateway",
            number: "3.5",
            title: "API Gateway",
            kind: "chapter",
            chapterDefinitionId: null,
            estimatedMinutes: 25,
            difficulty: "foundational",
            prerequisiteSlugs: ["3-4-load-balancer"],
            domain: null,
          },
        ],
      },
      {
        id: "bb-group-b",
        label: "Group B",
        title: "Compute",
        summary:
          "Why statelessness is the property that makes compute cheap to scale, and what it " +
          "takes to actually scale it out.",
        chapters: [
          {
            slug: "3-6-stateless-services",
            number: "3.6",
            title: "Stateless Services",
            kind: "chapter",
            chapterDefinitionId: null,
            estimatedMinutes: 20,
            difficulty: "foundational",
            prerequisiteSlugs: ["3-5-api-gateway"],
            domain: null,
          },
          {
            slug: "3-7-sessions-and-state-management",
            number: "3.7",
            title: "Sessions & State Management",
            kind: "chapter",
            chapterDefinitionId: null,
            estimatedMinutes: 25,
            difficulty: "foundational",
            prerequisiteSlugs: ["3-6-stateless-services"],
            domain: null,
          },
          {
            slug: "3-8-horizontal-scaling",
            number: "3.8",
            title: "Horizontal Scaling",
            kind: "chapter",
            chapterDefinitionId: null,
            estimatedMinutes: 25,
            difficulty: "foundational",
            prerequisiteSlugs: ["3-7-sessions-and-state-management"],
            domain: null,
          },
          {
            slug: "3-9-service-discovery",
            number: "3.9",
            title: "Service Discovery",
            kind: "chapter",
            chapterDefinitionId: null,
            estimatedMinutes: 20,
            difficulty: "foundational",
            prerequisiteSlugs: ["3-8-horizontal-scaling"],
            domain: null,
          },
        ],
      },
      {
        id: "bb-group-c",
        label: "Group C",
        title: "Data",
        summary:
          "What a database actually guarantees, when to reach for something other than SQL, " +
          "and how copies and partitions change the guarantees.",
        chapters: [
          {
            slug: "3-10-databases",
            number: "3.10",
            title: "Databases",
            kind: "chapter",
            chapterDefinitionId: null,
            estimatedMinutes: 25,
            difficulty: "intermediate",
            prerequisiteSlugs: ["3-9-service-discovery"],
            domain: null,
          },
          {
            slug: "3-11-sql-vs-nosql",
            number: "3.11",
            title: "SQL vs. NoSQL",
            kind: "chapter",
            chapterDefinitionId: null,
            estimatedMinutes: 25,
            difficulty: "intermediate",
            prerequisiteSlugs: ["3-10-databases"],
            domain: null,
          },
          {
            slug: "3-12-replication",
            number: "3.12",
            title: "Replication",
            kind: "chapter",
            chapterDefinitionId: null,
            estimatedMinutes: 30,
            difficulty: "intermediate",
            prerequisiteSlugs: ["3-11-sql-vs-nosql"],
            domain: null,
          },
          {
            slug: "3-13-sharding",
            number: "3.13",
            title: "Sharding",
            kind: "chapter",
            chapterDefinitionId: null,
            estimatedMinutes: 30,
            difficulty: "intermediate",
            prerequisiteSlugs: ["3-12-replication"],
            domain: null,
          },
        ],
      },
      {
        id: "bb-group-d",
        label: "Group D",
        title: "Performance",
        summary:
          "The highest-leverage scaling tool (caching) plus the two derived-data problems it " +
          "creates: caching at the edge and a second store that must stay in sync.",
        chapters: [
          {
            slug: "3-14-caching",
            number: "3.14",
            title: "Caching",
            kind: "chapter",
            chapterDefinitionId: null,
            estimatedMinutes: 35,
            difficulty: "intermediate",
            prerequisiteSlugs: ["3-13-sharding"],
            domain: null,
          },
          {
            slug: "3-15-cdn",
            number: "3.15",
            title: "CDN",
            kind: "chapter",
            chapterDefinitionId: null,
            estimatedMinutes: 25,
            difficulty: "intermediate",
            prerequisiteSlugs: ["3-14-caching"],
            domain: null,
          },
          {
            slug: "3-16-search-systems",
            number: "3.16",
            title: "Search Systems",
            kind: "chapter",
            chapterDefinitionId: null,
            estimatedMinutes: 30,
            difficulty: "intermediate",
            prerequisiteSlugs: ["3-15-cdn"],
            domain: null,
          },
          {
            slug: "checkpoint-r1-a-site-that-stays-up",
            number: "R1",
            title: "Checkpoint · A Site That Stays Up",
            kind: "checkpoint",
            chapterDefinitionId: null,
            estimatedMinutes: 45,
            difficulty: "intermediate",
            prerequisiteSlugs: ["3-16-search-systems"],
            domain: null,
          },
        ],
      },
      {
        id: "bb-group-e",
        label: "Group E",
        title: "Asynchronous Systems",
        summary:
          "Everything so far has been synchronous request/response - work that happens later, " +
          "and what happens when it fails.",
        chapters: [
          {
            slug: "3-17-message-queues",
            number: "3.17",
            title: "Message Queues",
            kind: "chapter",
            chapterDefinitionId: null,
            estimatedMinutes: 35,
            difficulty: "intermediate",
            // §17: Groups E and F are both gated on R1 only, not on each
            // other - the one sanctioned branch in Part 3.
            prerequisiteSlugs: ["checkpoint-r1-a-site-that-stays-up"],
            domain: null,
          },
          {
            slug: "3-18-event-driven-architecture",
            number: "3.18",
            title: "Event-Driven Architecture",
            kind: "chapter",
            chapterDefinitionId: null,
            estimatedMinutes: 35,
            difficulty: "intermediate",
            prerequisiteSlugs: ["3-17-message-queues"],
            domain: null,
          },
          {
            slug: "3-19-background-jobs-and-scheduling",
            number: "3.19",
            title: "Background Jobs & Scheduling",
            kind: "chapter",
            chapterDefinitionId: null,
            estimatedMinutes: 25,
            difficulty: "intermediate",
            prerequisiteSlugs: ["3-18-event-driven-architecture"],
            domain: null,
          },
        ],
      },
      {
        id: "bb-group-f",
        label: "Group F",
        title: "Storage",
        summary:
          "Blobs, files, and what storage means once it spans machines - consistency models, " +
          "quorums, and CAP stated honestly.",
        chapters: [
          {
            slug: "3-20-object-storage",
            number: "3.20",
            title: "Object Storage",
            kind: "chapter",
            chapterDefinitionId: null,
            estimatedMinutes: 25,
            difficulty: "intermediate",
            // §17: parallel-eligible with Group E - both hang off R1.
            prerequisiteSlugs: ["checkpoint-r1-a-site-that-stays-up"],
            domain: null,
          },
          {
            slug: "3-21-file-storage",
            number: "3.21",
            title: "File Storage",
            kind: "chapter",
            chapterDefinitionId: null,
            estimatedMinutes: 20,
            difficulty: "intermediate",
            prerequisiteSlugs: ["3-20-object-storage"],
            domain: null,
          },
          {
            slug: "3-22-distributed-storage-concepts",
            number: "3.22",
            title: "Distributed Storage Concepts",
            kind: "chapter",
            chapterDefinitionId: null,
            estimatedMinutes: 30,
            difficulty: "intermediate",
            prerequisiteSlugs: ["3-21-file-storage"],
            domain: null,
          },
        ],
      },
      {
        id: "bb-group-g",
        label: "Group G",
        title: "Reliability",
        summary:
          "Timeouts, retries, rate limits, observability, and failover - the patterns that " +
          "keep an already-correct system running.",
        chapters: [
          {
            slug: "3-23-reliability-patterns",
            number: "3.23",
            title: "Reliability Patterns",
            kind: "chapter",
            chapterDefinitionId: null,
            estimatedMinutes: 30,
            difficulty: "advanced",
            // §17: Group G needs both Group E and Group F complete.
            prerequisiteSlugs: [
              "3-19-background-jobs-and-scheduling",
              "3-22-distributed-storage-concepts",
            ],
            domain: null,
          },
          {
            slug: "3-24-rate-limiting",
            number: "3.24",
            title: "Rate Limiting",
            kind: "chapter",
            chapterDefinitionId: null,
            estimatedMinutes: 25,
            difficulty: "advanced",
            prerequisiteSlugs: ["3-23-reliability-patterns"],
            domain: null,
          },
          {
            slug: "3-25-observability",
            number: "3.25",
            title: "Observability",
            kind: "chapter",
            chapterDefinitionId: null,
            estimatedMinutes: 20,
            difficulty: "advanced",
            prerequisiteSlugs: ["3-24-rate-limiting"],
            domain: null,
          },
          {
            slug: "3-26-fault-tolerance",
            number: "3.26",
            title: "Fault Tolerance",
            kind: "chapter",
            chapterDefinitionId: null,
            estimatedMinutes: 35,
            difficulty: "advanced",
            prerequisiteSlugs: ["3-25-observability"],
            domain: null,
          },
          {
            slug: "checkpoint-r2-building-a-complete-backend",
            number: "R2",
            title: "Checkpoint · Building a Complete Backend",
            kind: "checkpoint",
            chapterDefinitionId: null,
            estimatedMinutes: 60,
            difficulty: "advanced",
            prerequisiteSlugs: ["3-26-fault-tolerance"],
            domain: null,
          },
          {
            slug: "checkpoint-r3-open-system-design",
            number: "R3",
            title: "Checkpoint · Open System Design",
            kind: "checkpoint",
            chapterDefinitionId: null,
            estimatedMinutes: 60,
            difficulty: "advanced",
            prerequisiteSlugs: ["checkpoint-r2-building-a-complete-backend"],
            domain: null,
          },
        ],
      },
    ],
  },
  "real-world-extraction": {
    id: "real-world-extraction",
    title: "Real World Extraction",
    subtitle: "Full system-design briefs. More than one architecture passes.",
    sections: [
      {
        id: "rwe-tier-1",
        label: "Tier 1",
        title: "Foundational Systems",
        summary:
          "First contact with open briefs while Part 3 is still in progress - tiny surfaces, " +
          "one crisp new problem each.",
        chapters: [
          {
            slug: "rwe-t1-bitly-url-shortener",
            number: null,
            title: "Bitly (URL Shortener)",
            kind: "chapter",
            // Re-homed from v1's RWE-1 bit.ly per §21.4 - same project.
            chapterDefinitionId: "rwe-dummy-1",
            estimatedMinutes: 75,
            difficulty: "intermediate",
            prerequisiteSlugs: ["checkpoint-r1-a-site-that-stays-up"],
            domain: "URL & metadata",
          },
          {
            slug: "rwe-t1-rate-limiter",
            number: null,
            title: "Rate Limiter",
            kind: "chapter",
            chapterDefinitionId: null,
            estimatedMinutes: 60,
            difficulty: "intermediate",
            prerequisiteSlugs: ["checkpoint-r1-a-site-that-stays-up"],
            domain: "Infrastructure",
          },
          {
            slug: "rwe-t1-distributed-cache",
            number: null,
            title: "Distributed Cache (Design One)",
            kind: "chapter",
            chapterDefinitionId: null,
            estimatedMinutes: 70,
            difficulty: "intermediate",
            prerequisiteSlugs: ["checkpoint-r1-a-site-that-stays-up"],
            domain: "Infrastructure",
          },
          {
            slug: "rwe-t1-metrics-monitoring",
            number: null,
            title: "Metrics Monitoring",
            kind: "chapter",
            chapterDefinitionId: null,
            estimatedMinutes: 65,
            difficulty: "intermediate",
            prerequisiteSlugs: ["checkpoint-r1-a-site-that-stays-up"],
            domain: "Infrastructure",
          },
        ],
      },
      {
        id: "rwe-tier-2",
        label: "Tier 2",
        title: "Applied Systems",
        summary:
          "The first multi-subsystem projects: every piece is familiar on its own, and the " +
          "composition is the lesson.",
        chapters: [
          {
            slug: "rwe-t2-notification-system",
            number: null,
            title: "Notification System",
            kind: "chapter",
            chapterDefinitionId: null,
            estimatedMinutes: 75,
            difficulty: "intermediate",
            prerequisiteSlugs: ["checkpoint-r2-building-a-complete-backend"],
            domain: "Messaging",
          },
          {
            slug: "rwe-t2-job-scheduler",
            number: null,
            title: "Job Scheduler",
            kind: "chapter",
            chapterDefinitionId: null,
            estimatedMinutes: 80,
            difficulty: "intermediate",
            prerequisiteSlugs: ["checkpoint-r2-building-a-complete-backend"],
            domain: "Scheduling",
          },
          {
            slug: "rwe-t2-leetcode",
            number: null,
            title: "LeetCode",
            kind: "chapter",
            chapterDefinitionId: null,
            estimatedMinutes: 75,
            difficulty: "intermediate",
            prerequisiteSlugs: ["checkpoint-r2-building-a-complete-backend"],
            domain: "Developer platforms",
          },
          {
            slug: "rwe-t2-price-tracking-service",
            number: null,
            title: "Price Tracking Service",
            kind: "chapter",
            chapterDefinitionId: null,
            estimatedMinutes: 80,
            difficulty: "intermediate",
            prerequisiteSlugs: ["checkpoint-r2-building-a-complete-backend"],
            domain: "Marketplaces",
          },
          {
            slug: "rwe-t2-online-chess",
            number: null,
            title: "Online Chess",
            kind: "chapter",
            chapterDefinitionId: null,
            estimatedMinutes: 90,
            difficulty: "intermediate",
            prerequisiteSlugs: ["checkpoint-r2-building-a-complete-backend"],
            domain: "Gaming",
          },
        ],
      },
      {
        id: "rwe-tier-3",
        label: "Tier 3",
        title: "Composite Systems",
        summary:
          "Full products with two or more interacting subsystems and real consistency stakes.",
        chapters: [
          {
            slug: "rwe-t3-google-drive",
            number: null,
            title: "Google Drive",
            kind: "chapter",
            chapterDefinitionId: null,
            estimatedMinutes: 90,
            difficulty: "advanced",
            prerequisiteSlugs: ["checkpoint-r3-open-system-design"],
            domain: "Storage & files",
          },
          {
            slug: "rwe-t3-google-docs",
            number: null,
            title: "Google Docs",
            kind: "chapter",
            chapterDefinitionId: null,
            estimatedMinutes: 100,
            difficulty: "advanced",
            prerequisiteSlugs: ["checkpoint-r3-open-system-design"],
            domain: "Storage & collaboration",
          },
          {
            slug: "rwe-t3-ad-click-aggregator",
            number: null,
            title: "Ad Click Aggregator",
            kind: "chapter",
            chapterDefinitionId: null,
            estimatedMinutes: 110,
            difficulty: "advanced",
            prerequisiteSlugs: ["checkpoint-r3-open-system-design"],
            domain: "Aggregation & ranking",
          },
          {
            slug: "rwe-t3-news-aggregator",
            number: null,
            title: "News Aggregator",
            kind: "chapter",
            chapterDefinitionId: null,
            estimatedMinutes: 90,
            difficulty: "advanced",
            prerequisiteSlugs: ["checkpoint-r3-open-system-design"],
            domain: "Search & discovery",
          },
          {
            slug: "rwe-t3-facebook-post-search",
            number: null,
            title: "Facebook Post Search",
            kind: "chapter",
            chapterDefinitionId: null,
            estimatedMinutes: 100,
            difficulty: "advanced",
            prerequisiteSlugs: ["checkpoint-r3-open-system-design"],
            domain: "Search & discovery",
          },
          {
            slug: "rwe-t3-yelp",
            number: null,
            title: "Yelp",
            kind: "chapter",
            chapterDefinitionId: null,
            estimatedMinutes: 90,
            difficulty: "advanced",
            prerequisiteSlugs: ["checkpoint-r3-open-system-design"],
            domain: "Search & discovery",
          },
          {
            slug: "rwe-t3-payment-system",
            number: null,
            title: "Payment System",
            kind: "chapter",
            chapterDefinitionId: null,
            estimatedMinutes: 110,
            difficulty: "advanced",
            prerequisiteSlugs: ["checkpoint-r3-open-system-design"],
            domain: "Marketplaces",
          },
          {
            slug: "rwe-t3-online-auction",
            number: null,
            title: "Online Auction",
            kind: "chapter",
            chapterDefinitionId: null,
            estimatedMinutes: 100,
            difficulty: "advanced",
            prerequisiteSlugs: ["checkpoint-r3-open-system-design"],
            domain: "Marketplaces",
          },
          {
            slug: "rwe-t3-irctc-train-booking",
            number: null,
            title: "IRCTC (Train Booking)",
            kind: "chapter",
            chapterDefinitionId: null,
            estimatedMinutes: 120,
            difficulty: "advanced",
            prerequisiteSlugs: ["checkpoint-r3-open-system-design"],
            domain: "Booking",
          },
        ],
      },
      {
        id: "rwe-tier-4",
        label: "Tier 4",
        title: "Flagship Systems",
        summary:
          "The interview canon's centerpieces - each inverts or stresses a foundational " +
          "assumption.",
        chapters: [
          {
            slug: "rwe-t4-whatsapp",
            number: null,
            title: "WhatsApp",
            kind: "chapter",
            chapterDefinitionId: null,
            estimatedMinutes: 150,
            difficulty: "advanced",
            // §15.2: unlocks at R3 + any 2 Tier-3 projects. `prerequisiteSlugs`
            // has no quorum ("any N of") semantics yet and nothing reads
            // this field in 3.0.0, so this lists R3 plus all nine Tier-3
            // candidates rather than approximating a threshold incorrectly
            // as a strict AND (same convention the v1 manifest used for its
            // one Netflix example, now generalized to every Tier 4/5 entry).
            prerequisiteSlugs: [
              "checkpoint-r3-open-system-design",
              "rwe-t3-google-drive",
              "rwe-t3-google-docs",
              "rwe-t3-ad-click-aggregator",
              "rwe-t3-news-aggregator",
              "rwe-t3-facebook-post-search",
              "rwe-t3-yelp",
              "rwe-t3-payment-system",
              "rwe-t3-online-auction",
              "rwe-t3-irctc-train-booking",
            ],
            domain: "Messaging",
          },
          {
            slug: "rwe-t4-instagram",
            number: null,
            title: "Instagram",
            kind: "chapter",
            chapterDefinitionId: null,
            estimatedMinutes: 130,
            difficulty: "advanced",
            prerequisiteSlugs: [
              "checkpoint-r3-open-system-design",
              "rwe-t3-google-drive",
              "rwe-t3-google-docs",
              "rwe-t3-ad-click-aggregator",
              "rwe-t3-news-aggregator",
              "rwe-t3-facebook-post-search",
              "rwe-t3-yelp",
              "rwe-t3-payment-system",
              "rwe-t3-online-auction",
              "rwe-t3-irctc-train-booking",
            ],
            domain: "Social & feeds",
          },
          {
            slug: "rwe-t4-inshorts-news-feed",
            number: null,
            title: "InShorts News Feed",
            kind: "chapter",
            chapterDefinitionId: null,
            estimatedMinutes: 120,
            difficulty: "advanced",
            prerequisiteSlugs: [
              "checkpoint-r3-open-system-design",
              "rwe-t3-google-drive",
              "rwe-t3-google-docs",
              "rwe-t3-ad-click-aggregator",
              "rwe-t3-news-aggregator",
              "rwe-t3-facebook-post-search",
              "rwe-t3-yelp",
              "rwe-t3-payment-system",
              "rwe-t3-online-auction",
              "rwe-t3-irctc-train-booking",
            ],
            domain: "Social & feeds",
          },
          {
            slug: "rwe-t4-youtube",
            number: null,
            title: "YouTube",
            kind: "chapter",
            chapterDefinitionId: null,
            estimatedMinutes: 140,
            difficulty: "advanced",
            prerequisiteSlugs: [
              "checkpoint-r3-open-system-design",
              "rwe-t3-google-drive",
              "rwe-t3-google-docs",
              "rwe-t3-ad-click-aggregator",
              "rwe-t3-news-aggregator",
              "rwe-t3-facebook-post-search",
              "rwe-t3-yelp",
              "rwe-t3-payment-system",
              "rwe-t3-online-auction",
              "rwe-t3-irctc-train-booking",
            ],
            domain: "Video & streaming",
          },
          {
            slug: "rwe-t4-uber",
            number: null,
            title: "Uber",
            kind: "chapter",
            chapterDefinitionId: null,
            estimatedMinutes: 140,
            difficulty: "advanced",
            prerequisiteSlugs: [
              "checkpoint-r3-open-system-design",
              "rwe-t3-google-drive",
              "rwe-t3-google-docs",
              "rwe-t3-ad-click-aggregator",
              "rwe-t3-news-aggregator",
              "rwe-t3-facebook-post-search",
              "rwe-t3-yelp",
              "rwe-t3-payment-system",
              "rwe-t3-online-auction",
              "rwe-t3-irctc-train-booking",
            ],
            domain: "Location & mobility",
          },
          {
            slug: "rwe-t4-doordash-zomato",
            number: null,
            title: "DoorDash / Zomato",
            kind: "chapter",
            chapterDefinitionId: null,
            estimatedMinutes: 150,
            difficulty: "advanced",
            prerequisiteSlugs: [
              "checkpoint-r3-open-system-design",
              "rwe-t3-google-drive",
              "rwe-t3-google-docs",
              "rwe-t3-ad-click-aggregator",
              "rwe-t3-news-aggregator",
              "rwe-t3-facebook-post-search",
              "rwe-t3-yelp",
              "rwe-t3-payment-system",
              "rwe-t3-online-auction",
              "rwe-t3-irctc-train-booking",
            ],
            domain: "Location & mobility",
          },
          {
            slug: "rwe-t4-tinder",
            number: null,
            title: "Tinder",
            kind: "chapter",
            chapterDefinitionId: null,
            estimatedMinutes: 120,
            difficulty: "advanced",
            prerequisiteSlugs: [
              "checkpoint-r3-open-system-design",
              "rwe-t3-google-drive",
              "rwe-t3-google-docs",
              "rwe-t3-ad-click-aggregator",
              "rwe-t3-news-aggregator",
              "rwe-t3-facebook-post-search",
              "rwe-t3-yelp",
              "rwe-t3-payment-system",
              "rwe-t3-online-auction",
              "rwe-t3-irctc-train-booking",
            ],
            domain: "Matching",
          },
          {
            slug: "rwe-t4-robinhood",
            number: null,
            title: "Robinhood",
            kind: "chapter",
            chapterDefinitionId: null,
            estimatedMinutes: 140,
            difficulty: "advanced",
            prerequisiteSlugs: [
              "checkpoint-r3-open-system-design",
              "rwe-t3-google-drive",
              "rwe-t3-google-docs",
              "rwe-t3-ad-click-aggregator",
              "rwe-t3-news-aggregator",
              "rwe-t3-facebook-post-search",
              "rwe-t3-yelp",
              "rwe-t3-payment-system",
              "rwe-t3-online-auction",
              "rwe-t3-irctc-train-booking",
            ],
            domain: "Marketplaces",
          },
          {
            slug: "rwe-t4-google-maps",
            number: null,
            title: "Google Maps",
            kind: "chapter",
            chapterDefinitionId: null,
            estimatedMinutes: 130,
            difficulty: "advanced",
            prerequisiteSlugs: [
              "checkpoint-r3-open-system-design",
              "rwe-t3-google-drive",
              "rwe-t3-google-docs",
              "rwe-t3-ad-click-aggregator",
              "rwe-t3-news-aggregator",
              "rwe-t3-facebook-post-search",
              "rwe-t3-yelp",
              "rwe-t3-payment-system",
              "rwe-t3-online-auction",
              "rwe-t3-irctc-train-booking",
            ],
            domain: "Maps",
          },
        ],
      },
      {
        id: "rwe-tier-5",
        label: "Tier 5",
        title: "Frontier Systems",
        summary:
          "Deep single-problem systems: each takes one hard sub-problem and makes it the " +
          "whole project.",
        chapters: [
          {
            slug: "rwe-t5-google-docs-realtime-collaboration",
            number: null,
            title: "Google Docs: Real-time Collaboration",
            kind: "chapter",
            chapterDefinitionId: null,
            estimatedMinutes: 150,
            difficulty: "advanced",
            // §15.2: unlocks at any 2 of the nine Tier-4 projects - same
            // "any N of" caveat as Tier 4's own gate (see WhatsApp above).
            prerequisiteSlugs: [
              "rwe-t4-whatsapp",
              "rwe-t4-instagram",
              "rwe-t4-inshorts-news-feed",
              "rwe-t4-youtube",
              "rwe-t4-uber",
              "rwe-t4-doordash-zomato",
              "rwe-t4-tinder",
              "rwe-t4-robinhood",
              "rwe-t4-google-maps",
            ],
            domain: "Collaboration",
          },
          {
            slug: "rwe-t5-facebook-live-comments",
            number: null,
            title: "Facebook Live Comments",
            kind: "chapter",
            chapterDefinitionId: null,
            estimatedMinutes: 130,
            difficulty: "advanced",
            prerequisiteSlugs: [
              "rwe-t4-whatsapp",
              "rwe-t4-instagram",
              "rwe-t4-inshorts-news-feed",
              "rwe-t4-youtube",
              "rwe-t4-uber",
              "rwe-t4-doordash-zomato",
              "rwe-t4-tinder",
              "rwe-t4-robinhood",
              "rwe-t4-google-maps",
            ],
            domain: "Social & feeds",
          },
          {
            slug: "rwe-t5-youtube-top-k",
            number: null,
            title: "YouTube Top K",
            kind: "chapter",
            chapterDefinitionId: null,
            estimatedMinutes: 130,
            difficulty: "advanced",
            prerequisiteSlugs: [
              "rwe-t4-whatsapp",
              "rwe-t4-instagram",
              "rwe-t4-inshorts-news-feed",
              "rwe-t4-youtube",
              "rwe-t4-uber",
              "rwe-t4-doordash-zomato",
              "rwe-t4-tinder",
              "rwe-t4-robinhood",
              "rwe-t4-google-maps",
            ],
            domain: "Video & streaming",
          },
          {
            slug: "rwe-t5-strava",
            number: null,
            title: "Strava",
            kind: "chapter",
            chapterDefinitionId: null,
            estimatedMinutes: 120,
            difficulty: "advanced",
            prerequisiteSlugs: [
              "rwe-t4-whatsapp",
              "rwe-t4-instagram",
              "rwe-t4-inshorts-news-feed",
              "rwe-t4-youtube",
              "rwe-t4-uber",
              "rwe-t4-doordash-zomato",
              "rwe-t4-tinder",
              "rwe-t4-robinhood",
              "rwe-t4-google-maps",
            ],
            domain: "Location & mobility",
          },
          {
            slug: "rwe-t5-web-crawler",
            number: null,
            title: "Web Crawler",
            kind: "chapter",
            chapterDefinitionId: null,
            estimatedMinutes: 130,
            difficulty: "advanced",
            prerequisiteSlugs: [
              "rwe-t4-whatsapp",
              "rwe-t4-instagram",
              "rwe-t4-inshorts-news-feed",
              "rwe-t4-youtube",
              "rwe-t4-uber",
              "rwe-t4-doordash-zomato",
              "rwe-t4-tinder",
              "rwe-t4-robinhood",
              "rwe-t4-google-maps",
            ],
            domain: "Search & discovery",
          },
        ],
      },
    ],
  },
};
