import {
  AppWindow,
  Archive,
  ArrowLeftRight,
  Boxes,
  Compass,
  Cog,
  Copy,
  Crown,
  Database,
  DoorOpen,
  Gauge,
  Globe,
  Layers,
  ListOrdered,
  Lock,
  MailWarning,
  Monitor,
  Radio,
  Search,
  Server,
  Shield,
  Shuffle,
  Timer,
  Users,
  Waves,
  Workflow,
  Zap,
  type LucideIcon,
} from "lucide-react";

/** Keyed by ComponentDefinition.icon — shared between ComponentNode and Palette so
 * both render the same glyph per component. */
export const iconMap: Record<string, LucideIcon> = {
  monitor: Monitor,
  "app-window": AppWindow,
  compass: Compass,
  globe: Globe,
  "arrow-left-right": ArrowLeftRight,
  "door-open": DoorOpen,
  shuffle: Shuffle,
  shield: Shield,
  server: Server,
  cog: Cog,
  timer: Timer,
  zap: Zap,
  database: Database,
  layers: Layers,
  copy: Copy,
  archive: Archive,
  search: Search,
  gauge: Gauge,
  boxes: Boxes,
  "list-ordered": ListOrdered,
  waves: Waves,
  radio: Radio,
  "mail-warning": MailWarning,
  workflow: Workflow,
  crown: Crown,
  users: Users,
  lock: Lock,
};
